Python. Homework #2. Task #1. Власов Илья
GirZ0n/SPBU-Homework-4 pull request #6
Opened 2021-02-28 17:00 UTC by GirZ0n

2021-03-01 13:58 UTC, nbirillo commented
Should I review this PR since you have a TODO?

2021-03-09 12:59 UTC, nbirillo requested changes
Great! I have only one comment

2021-03-09 12:59 UTC, nbirillo commented on homework/homework2/task1/curry.py
> +def curry_explicit(function: Callable, arity: int) -> Callable:
Please, try to fix your functions for this case:
```
f4 = curry_explicit(print, 4)
g4 = uncurry_explicit(f4, 4)
f2 = f4(10)(20)
g2 = uncurry_explicit(f2, 2)
print('---')
f4(5)(15)(25)(35)
f2(30)(40)
print('---')
g4(5, 15, 25, 35)
g2(30, 40)
```
The expected output in this case:
```
---
5 15 25 35
10 20 30 40
---
5 15 25 35
10 20 30 40
```
But in your case, you will have an error

2021-03-12 08:46 UTC, nbirillo requested changes
Great! I hope it is the last comment

2021-03-12 08:46 UTC, nbirillo commented on homework/homework2/task1/curry.py
> +def curry_explicit(function: Callable, arity: int) -> Callable:
Sorry, but I found another bug:
```
f0 = curry_explicit(lambda *xs: print(xs), 0)

print('try nullary:')
f0()

try:
    print('try unary:')
    f0(1)
except Exception as e:
    print('-- expected exception.')

try:
    print('try nullary-nullary:')
    f0()()
except Exception as e:
    print('-- expected exception.')
```
The expected output is:
```
try nullary:
()
try unary:
-- expected exception.
try nullary-nullary:
()
-- expected exception.
```
Your output is:
```
try nullary:
()
try unary:
(1,)
try nullary-nullary:
()
-- expected exception.
```

2021-03-13 13:06 UTC, SpirinEgor approved these changes

2021-03-13 13:06 UTC, merged